name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y guile-3.0 guile-3.0-dev emacs-nox direnv

    - name: Configure
      run: ./configure

    - name: Build
      run: make all

    - name: Run tests
      run: make test

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Lint code
      continue-on-error: true  # Don't fail on linting errors
      run: make lint